- hosts: 192.168.33.10 #wordpress
  become: true
  vars:
    wordpress_url: https://ja.wordpress.org/wordpress-4.4.2-ja.tar.gz
    remote_usr: user
  tasks:
    - name: 必要パッケージのyumインストール
      yum: name="{{item}}" state=latest
      with_items:
        - php
        - php-mysql
        - httpd
        - mariadb
        - mariadb-server
        - MySQL-python

    - name: firewalldでHTTPを許可
      firewalld: permanent=True service=http state=enabled

    - name: タイムゾーンの設定
      ini_file: >
        dest=/etx/php.ini
        section=Date
        option=date.timezone
        value='"Asis/Tokyo"'

    - name: wordpressの展開
      unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no

    - name: wordpressの所有権をapacheに変更
      file: path=/var/www/html/wordpress/ owner=apache group=apache recurse=yes

    - name: 各種サービスの再起動
      service: name="{{item}}" state=started enabled=yes
      with_items:
        - mariadb
        - httpd
